NiFTyRent/nft-rental

contract/src/externals.rs, contract/src/lib.rs
[WEB-21](https://linear.app/web3cows/issue/WEB-21/token-transfer-failure-is-not-properly-handled)
Added promise handle for leanding_accept. Lease records table in the contract will only be updated if NFT has been successfully transferred from owner to  lease contract; If any error occured during handling, the NFT transfer will be revert. 
Updates:
- use nft_transfer_call method defined in [NEP171](https://nomicon.io/Standards/Tokens/NonFungibleToken/Core)
- implemented nft_on_approve and return a bool accordingly. Return of this method will be picked up by nft_resolve_transfer in NFT contract.
- created externals.rs file to keep cross contract call related features
- minor format / comment adjustment
=> [WEB-12] Token transfer failure is not properly handled

frontend/src/NftContract.js
Increase the deposit amount and gas.
Fix the error when create lease on Mintbase NFTs.
```
{"index":0,"kind":{"ExecutionError":"Smart contract panicked: Requires storage deposit of at least 800000000000000000000 yoctoNEAR (store/src/approvals.rs, 40:9)"}}
```
=> Fix the error when create lease on Mintbase NFTs.

contract/src/externals.rs, contract/src/lib.rs, package.json
Run `yarn lint` at the root directory of the code repo to do the formating and code linting.
The lint warnings will be cleaned in the following PR.
See more: https://github.com/rust-lang/rust-clippy
=> Setup up rust linter

contract/src/lib.rs, frontend/src/AcceptBorrowingPage.jsx, frontend/src/NftContract.js, integration-tests/tests/integration.rs
`amount_near` is a misleading name, it's actually in the unit of yacto Near.
Also change to use U128 as the argument data type, so that the near sdk will handle both integer or string a parameter automatically.
=> Rename `amount_near` to `price`

contract/src/externals.rs, contract/src/lib.rs
As the first step of implementing the payout (i.e. Royalty) functionality, we store the payout info given by the NFT contract when transfering the NFT to our contract. This info will be later used to split the rent payment to all relavant parties when the NFT got claimed back.
It also replaced the nft_transfer callback with a private contract function called `activate_lease`. This is a better way to handle multiple async operation (i.e. promises) in a transcational way.
=> Request and store payout when activating lease

contract/src/externals.rs, contract/src/lib.rs
Added a `resolve_claim_back` private function to handle the steps after transfering the NFT back to the owner: 1. make the payment to all relevant parties, 2. clean up the lease record.
Also make the `internal_transfer_near` return a promise. It can be useful in the future we want to make sure such transfer indeed goes through with no issue.
=> Make payment according to the payout info.

contract/src/externals.rs, contract/src/lib.rs, integration-tests/tests/integration.rs
[NR-36](https://linear.app/niftyrent/issue/NR-36/lookup-functions-are-too-expensive)
- Added 2 lookup indices:  lease_ids_by_lender & lease_ids_by_borrower
- Adjusted code to reflect indices update (lease add, lease remove)
- Adjusted test cases and add new test cases for internal methods
- Unit test result:
- Integration test result:
=> [NR-36] Add indices for look up & unit tests

contract/src/lib.rs, integration-tests/tests/integration.rs
[NR-67](https://linear.app/niftyrent/issue/NR-67/add-index-to-optimise-get-borrower) 
[NR-42](https://linear.app/niftyrent/issue/NR-42/get-borrower-should-return-none-when-the-lease-is-expired)
Previously, get_borrower iterates the whole lease map to find the matching borrower. It is not gas efficient
The method is also not checking lease status, where only active lease should be counted
- A new index _lease_id_by_contract_addr_and_token_id_ is added, which can then use lease_map to get the matching borrower. This design is easier to be extended in the future when other lease info needs to be queried given (contract_addr, token_id). 
- Lease state check added in the method when matching lease is found
- Updated the method name to be more descriptive
- Adjusted code to maintain the new …
=> [NR67][NR42]Add index to support get_borrower & add lease state check to get_borrower

contract/src/lib.rs
When the lender attempts to accept the lending, payout will be calculated by the given NFT, and we will verify if the sum of payout equals to the lease price. If not, we will throw exception and abort the call. 
Test plan:
Unit test.
=> [NR-61] check the sum of the payout values should match the price

contract/src/lib.rs, demo_nft_contract/src/lib.rs
If the previous XCC (i.e. the NFT transfer step), fails, the lease activation should exit immediately.
=> activate_lease handles the promise failure.

integration-tests/README.md
Small PR to include unit tests description inside test document. 
Also updated test plan to include the newly added test on royalty split.
=> include unit test description in test document

contract/README.md
Small PR to removed the outdated Readme for contract file, that is auto-generated by near tutorial.
This is to remove any confusion for grantee reviewer. More description can be added later.
=> Remove outdated README for contract

demo_nft_contract/src/lib.rs
This method is a view method to return the payout info of the demo nft. 
Reference: https://docs.near.org/tutorials/nfts/royalty
=> Add `nft_payout` method to the demo nft

contract/src/externals.rs, contract/src/lib.rs, demo_nft_contract/src/lib.rs, integration-tests/tests/integration.rs
Use a cross contract call to fetch the payout info when creating the lease, i.e. when lender calls `nft_approve`
Set the payout info into the lease when initializing it instead of when transferring the token
Test plan:
integration test and unit test
=> [NR-75] Fetch payout info when creating the lease

contract/Cargo.lock, contract/Cargo.toml, contract/src/lib.rs, contract/src/utils.rs, integration-tests/Cargo.lock, integration-tests/Cargo.toml, integration-tests/tests/gas_usage.rs, integration-tests/tests/integration.rs, integration-tests/tests/utils.rs
Also:
1. Upgrade to the newest version near_contracts_standard to avoid breakage. (`hash_account_id` is deprecated in the newest version. We have to implement it by ourselves.)
2. Add a macro to compare structs by converting them into string.
=> Reuse LeaseCondition in the integration test

contract/src/lib.rs, contract/src/nft/internal.rs
[NR-109](https://linear.app/niftyrent/issue/NR-109/bug-fix-correctly-handle-payout-cases)
At claim back, we transfer NFT to the LEASE token owner and send the rent to the original lender (or payouts account if there is any). 
To support sending rent correctly with payouts, at LEASE nft minting (lease activate) stage, we automatically create a payout record internally, if the field is not provided at lease creation. This proxy payout record marks the original lender as the only account to receive all the rent.
=> Handle Payout of the under-leased NFT When Using LEASE token

contract/src/externals.rs, contract/src/lib.rs, integration-tests/tests/integration.rs
Passing u128 to the frontend causes the floating point number precision problem. Using U128 will fix it.
In general, U128 is a more friendly type for input and output. The only drawback is that it take a little more storage space. We can optimise it in the future if needed.
Re-submission of https://github.com/NiFTyRent/nft-rental/pull/52
=> Use U128 for the price field in LeaseCondition.

contract/src/nft/core.rs, contract/src/nft/enumeration.rs
The near_bindgen marco is missed for some methods in NFT implementation, causing the methods not exposed on chain.
This PR fixes it.
=> Bug Fix: add near_bindgen for nft methods

contract/src/lib.rs, contract/src/nft/core.rs, contract/src/nft/internal.rs
[NR-105](https://linear.app/niftyrent/issue/NR-105/add-support-for-events)
Emit event logs at the following places, as per the [Events](https://nomicon.io/Standards/Tokens/NonFungibleToken/Event) standard:
- at nft mint (or lease activation)
- at nft transfer
- at nft resolve transfer, when a transfer should be reverted
The implementation utilises near sdk's events type
MISC:
- 2 more unit tests added to check the event log output.
- a helper function added to generate easy to read dummy account id at testing
=> Add Support for Events Standard

contract/src/nft/core.rs, integration-tests/README.md, integration-tests/tests/integration.rs
- Adjust title to use the correct format. Currently, the title looks like following, "NiftyRent".
- Updated test plan in readme.
=> Fix LEASE NFT token Title & Update Test plan readme

contract/src/externals.rs, contract/src/lib.rs, integration-tests/tests/integration.rs
Add a new field `start_ts_nano` for lender to specify when he wants the lease to start. 
After a second thought, I think `active` actually is better than `ready`.
Test plan:
Unit test and integration test
=> [NR-125]add-lease-start-time

contract/src/lib.rs, integration-tests/tests/integration.rs
Check the `end_ts_nano` to return the current user. If the current block timestamp is earlier than the `end_ts_nano`, then the user of the given NFT is the borrower. 
Test plan:
Unit test and integration test
=> [NR-125] add-lease-start-time

contract/src/lib.rs, marketplace/src/externals.rs, marketplace/src/ft_callbacks.rs, marketplace/src/lib.rs
- Remove listing from marketplace record when both nft transfer and rent transfer succeeded
- Rename some variables to be more accurate.
P.S.
I am not quite fond of the design to put listing removal in the same XCC function for transferring rent. It does the work for now. I will think about other options to do the listing removal without introducing extra XCC.
=> Remove listing after it has been activated & Rename some variables

contract/src/externals.rs, contract/src/lib.rs, integration-tests/tests/integration.rs, marketplace/src/externals.rs, marketplace/src/ft_callbacks.rs, marketplace/src/lib.rs, marketplace/src/nft_callbacks.rs
**Context**
Adding a state to represent a lease that between NFT being transferred and waiting for Rent to be transferred.
This also helps the rent transferred from Marketplace to Core to know its targeting lease. 
After this PR, Lease state change will be:
- When Lease created after NFT transfer call: PendingOnRent
- When rent received after FT transfer call: Active
**Solution & Code Change**
- Added a PendingOnRent state for Lease in Core
- Instead of ft_transfer(), marketplace will now use ft_transfer_call() to transfer the rent to call, passing in the (nft_contract_id, token_id) as message to specify the target lease
- Adjusted marketplace listing_id to be (AccountId, TokenId). This is due to discussion that one nft token can not have more than one listings.
**Misc**
- After using …
=> Marketplace Implementation - Add PendingOnRent state for Lease

contract/src/lib.rs, marketplace/src/lib.rs
This fix the problem of panic in nft_on_transfer when using Mintbase's NFT. They have a limit of 35TGas.
=> Reduce gas allocation for XCCs

contract/src/lib.rs
[NF-152](https://linear.app/niftyrent/issue/NR-152/bug-fix-emit-event-for-nft-token-burn)
Ownership token is still shown in owner's wallet after the lease being claimed back. This is due to no token burning event being logged.
This PR added the nft burn event at the end of lease claim back.
MISC: trim off unused import
=> Emit nft burn event log after lease being claimed
